'use client';
import { useEffect, useRef, useState } from 'react';

type ModalKind = 'professores'|'equipamentos'|'treinos'|'depoimento'|null;

const professors = [
  {name:'Camila Rocha', role:'Musculação e recomposição corporal', position:'p1', formation:'Bacharel em Educação Física — UFMG, 2017', extra:'Pós-graduação em Fisiologia do Exercício e Treinamento Resistido', bio:'Especialista em hipertrofia, emagrecimento e treinamento feminino, com acompanhamento próximo e progressões seguras.'},
  {name:'Rafael Mendes', role:'Hipertrofia e força', position:'p2', formation:'Bacharel em Educação Física — PUC Minas, 2015', extra:'Pós-graduação em Biomecânica e Treinamento de Força', bio:'Trabalha força e performance com técnica, consistência e planos adaptados à rotina de cada aluno.'},
  {name:'Mariana Lopes', role:'Funcional e mobilidade', position:'p3', formation:'Bacharel em Educação Física — Universidade FUMEC, 2019', extra:'Especialização em Treinamento Funcional e Prevenção de Lesões', bio:'Combina mobilidade, condicionamento e consciência corporal para fazer o aluno se movimentar melhor.'},
  {name:'Lucas Azevedo', role:'Emagrecimento e condicionamento', position:'p4', formation:'Bacharel em Educação Física — UniBH, 2018', extra:'Pós-graduação em Condicionamento Físico e Personal Training', bio:'Cria treinos objetivos e progressivos para quem quer recuperar o fôlego, a disposição e a confiança.'},
];
const testimonials=[
  {name:'Ana Paula',goal:'Mais força e disposição',position:'t1',text:'Eu comecei com receio de não acompanhar o ritmo. Encontrei professores atentos, uma estrutura excelente e um ambiente que me faz querer voltar. Hoje me sinto mais forte dentro e fora da academia.'},
  {name:'Bruno Martins',goal:'Hipertrofia',position:'t2',text:'A diferença está no cuidado com o treino. Recebi orientação para evoluir de forma segura e finalmente passei a enxergar resultado de verdade.'},
  {name:'Fernanda Souza',goal:'Qualidade de vida',position:'t3',text:'A Power Shape entrou na minha rotina e mudou minha energia. O espaço é acolhedor, os equipamentos são ótimos e sempre encontro ajuda quando preciso.'},
  {name:'Diego Alves',goal:'Condicionamento',position:'t4',text:'Voltei a treinar depois de muito tempo e fui avançando no meu ritmo. Hoje tenho mais fôlego, mais disciplina e vontade de superar a próxima meta.'},
  {name:'Juliana Ribeiro',goal:'Recomposição corporal',position:'t5',text:'O acompanhamento fez toda a diferença. Aprendi a executar os movimentos, parei de treinar no automático e passei a enxergar evolução semana após semana.'},
  {name:'Carlos Henrique',goal:'Mobilidade e saúde',position:'t6',text:'Encontrei um treino que respeita meu momento e ao mesmo tempo me desafia. Minha disposição melhorou e a academia virou parte da minha rotina.'},
];

export default function Home(){
 const [modal,setModal]=useState<ModalKind>(null); const [quote,setQuote]=useState(0); const [menu,setMenu]=useState(false); const [activePhoto,setActivePhoto]=useState(0); const storyRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(modal==='depoimento')return;const t=setTimeout(()=>setQuote(q=>(q+1)%testimonials.length),9000);return()=>clearTimeout(t)},[quote,modal]);
 useEffect(()=>{const items=storyRef.current?.querySelectorAll('figure');if(!items)return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActivePhoto(Number((e.target as HTMLElement).dataset.index))}),{rootMargin:'-32% 0px -32% 0px',threshold:.25});items.forEach(item=>observer.observe(item));return()=>observer.disconnect()},[]);
 useEffect(()=>{document.body.style.overflow=modal?'hidden':'';return()=>{document.body.style.overflow=''}},[modal]);
 const open=(kind:ModalKind)=>setModal(kind);
 return <main>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'HealthClub',name:'Power Shape CT',url:'https://powershapect.com.br/',telephone:'+55 31 9215-5412',address:{'@type':'PostalAddress',streetAddress:'R. do Ouro, 918',addressLocality:'Belo Horizonte',addressRegion:'MG',postalCode:'30220-000',addressCountry:'BR'},openingHours:['Mo-Fr 05:00-22:00','Sa 08:00-15:00','Su 09:00-12:00']})}}/>
  <header className="topbar">
   <a className="brand" href="#inicio" aria-label="Power Shape CT — início"><img src="/logo-power-shape.png" alt="Power Shape CT"/></a>
   <nav aria-label="Navegação principal"><a href="#estrutura">Estrutura</a><a href="#experiencias">Experiências</a><a href="#sobre">Quem somos</a><a href="#depoimentos">Depoimentos</a><a href="#localizacao">Localização</a></nav>
   <a className="nav-cta" href="https://wa.me/553192155412" target="_blank" rel="noreferrer">Conversar no WhatsApp ↗</a>
   <button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Abrir menu" aria-expanded={menu}>☰</button>
   {menu&&<div className="mobile-nav"><a href="#estrutura" onClick={()=>setMenu(false)}>Estrutura</a><a href="#experiencias" onClick={()=>setMenu(false)}>Experiências</a><a href="#sobre" onClick={()=>setMenu(false)}>Quem somos</a><a href="#depoimentos" onClick={()=>setMenu(false)}>Depoimentos</a><a href="#localizacao" onClick={()=>setMenu(false)}>Localização</a></div>}
  </header>

  <section id="inicio" className="hero"><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">ACADEMIA NO SERRA · BELO HORIZONTE</p><h1>Seu corpo pede <em>potência.</em><br/>A Power Shape entrega.</h1><p className="hero-lead">Equipamentos modernos, professores qualificados e treinos que transformam esforço em resultado.</p><div className="hero-actions"><a className="button primary" href="https://wa.me/553192155412" target="_blank" rel="noreferrer">Quero começar</a><a className="button ghost" href="#estrutura">Conhecer a estrutura ↓</a></div></div><div className="hero-stamp"><strong>25</strong><span>anos de<br/>movimento</span></div><div className="scroll-note">ROLE PARA SENTIR A ENERGIA <span>↓</span></div></section>

  <section className="manifest"><p>Há 25 anos transformando disciplina em força, saúde e confiança.</p><div className="ticker"><div className="ticker-track"><span>FORÇA · MOVIMENTO · EVOLUÇÃO · POTÊNCIA · FORÇA · MOVIMENTO · EVOLUÇÃO · POTÊNCIA ·&nbsp;</span><span aria-hidden="true">FORÇA · MOVIMENTO · EVOLUÇÃO · POTÊNCIA · FORÇA · MOVIMENTO · EVOLUÇÃO · POTÊNCIA ·&nbsp;</span></div></div></section>

  <section id="estrutura" className="section gallery-section"><div className="section-head"><div><p className="eyebrow">NOSSO ESPAÇO</p><h2>Onde a sua evolução<br/><i>ganha forma.</i></h2></div><p>Você não precisa esperar pela motivação perfeita. Precisa de um ambiente que faça você querer voltar. Deslize para conhecer cada parte da experiência Power Shape.</p></div><div className="folder-experience"><div className="folder-tabs">{['Estrutura que inspira','Equipamentos de ponta','Seu novo ritmo','Treine com liberdade','Potência em cada detalhe'].map((label,i)=><button key={label} className={i===activePhoto?'active':i<activePhoto?'passed':''} onClick={()=>storyRef.current?.querySelector(`[data-index="${i}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}><span>0{i+1}</span>{label}</button>)}</div><div className="story-gallery" ref={storyRef}>{[
   ['/academia-4.jpg','Estrutura que inspira','Área de musculação da Power Shape CT no Serra'],['/academia-1.jpg','Equipamentos de ponta','Equipamentos modernos da academia Power Shape CT'],['/academia-5.jpg','Seu novo ritmo','Ambiente interno da academia em Belo Horizonte'],['/academia-2.jpg','Treine com liberdade','Espaço para musculação e condicionamento físico'],['/academia-3.jpg','Potência em cada detalhe','Estrutura de treino Power Shape CT']
  ].map((photo,i)=><figure key={photo[0]} data-index={i} className={i===activePhoto?'story-photo active':i<activePhoto?'story-photo passed':'story-photo'}><img src={photo[0]} alt={photo[2]}/><figcaption><span>0{i+1}</span><b>{photo[1]}</b></figcaption></figure>)}</div></div></section>

  <section id="experiencias" className="section experience"><p className="eyebrow">A EXPERIÊNCIA POWER SHAPE</p><h2>Seu objetivo.<br/>Nossa <i>estrutura.</i></h2><div className="experience-grid"><button onClick={()=>open('professores')}><span>01</span><h3>Professores<br/>qualificados</h3><p>Formação acadêmica, especializações e orientação de perto.</p><b>CONHECER EQUIPE ↗</b></button><button onClick={()=>open('equipamentos')}><span>02</span><h3>Equipamentos<br/>de ponta</h3><p>Recursos modernos para diferentes treinos e objetivos.</p><b>VER EQUIPAMENTOS ↗</b></button><button onClick={()=>open('treinos')}><span>03</span><h3>Treinos<br/>personalizados</h3><p>Progressões inteligentes para transformar esforço em evolução.</p><b>EXPLORAR TREINOS ↗</b></button></div></section>

  <section id="sobre" className="about"><div className="about-image"><img src="/academia-5.jpg" alt="Academia Power Shape CT no bairro Serra"/><span>25</span></div><div className="about-copy"><p className="eyebrow">QUEM SOMOS</p><h2>Força, evolução e<br/><i>histórias reais.</i></h2><p>A Power Shape CT é uma academia no bairro Serra, em Belo Horizonte, criada para quem busca mais do que simplesmente treinar. Estrutura moderna, equipamentos de qualidade e acompanhamento profissional se encontram em um ambiente acolhedor e intenso.</p><p>Seja para ganhar força, melhorar o condicionamento, emagrecer ou recuperar a confiança no próprio corpo, aqui cada repetição tem propósito.</p><div className="about-metrics"><div><b>25</b><span>anos de tradição</span></div><div><b>7/7</b><span>dias por semana</span></div><div><b>1:1</b><span>atenção humana</span></div></div></div></section>

  <section id="depoimentos" className="section testimonials"><div className="section-head"><div><p className="eyebrow">DEPOIMENTOS</p><h2>Quem treina,<br/><i>sente a diferença.</i></h2></div><div className="quote-controls"><button onClick={()=>setQuote((quote-1+testimonials.length)%testimonials.length)} aria-label="Depoimento anterior">←</button><button onClick={()=>setQuote((quote+1)%testimonials.length)} aria-label="Próximo depoimento">→</button></div></div><div className="quote-viewport"><div className="quote-track">{[quote,(quote+1)%testimonials.length,(quote+2)%testimonials.length].map((idx,slot)=>{const t=testimonials[idx];return <button key={t.name} className={slot===0?'quote active':'quote'} onClick={()=>{setQuote(idx);open('depoimento')}}><div className={'quote-photo '+t.position}><img src="/depoimentos-grid.png" alt={'Retrato ilustrativo de '+t.name}/></div><p>“{t.text.slice(0,118)}...”</p><h3>{t.name}</h3><small>{t.goal}</small><b>LER HISTÓRIA COMPLETA ↗</b></button>})}</div></div><div className="quote-dots">{testimonials.map((t,i)=><button key={t.name} className={i===quote?'active':''} onClick={()=>setQuote(i)} aria-label={'Ver depoimento de '+t.name}/>)}</div><p className="prototype-note">* Depoimentos e personagens ilustrativos para apresentação do protótipo.</p></section>

  <section id="localizacao" className="location"><div className="location-call"><p className="eyebrow">ESTAMOS PERTO DE VOCÊ</p><h2>Seu treino<br/>está logo <i>ali.</i></h2><p>Na Rua do Ouro, no coração do bairro Serra. Clique no mapa, trace sua rota e venha sentir a energia da Power Shape.</p><a className="button primary" href="https://www.google.com/maps/search/?api=1&query=R.%20do%20Ouro%2C%20918%20Serra%20Belo%20Horizonte" target="_blank" rel="noreferrer">ABRIR NO GOOGLE MAPS ↗</a></div><a className="map map-link" href="https://www.google.com/maps/search/?api=1&query=R.%20do%20Ouro%2C%20918%20Serra%20Belo%20Horizonte" target="_blank" rel="noreferrer" aria-label="Abrir localização da Power Shape CT no Google Maps"><iframe title="Mapa da Power Shape CT" loading="lazy" src="https://maps.google.com/maps?q=R.%20do%20Ouro%2C%20918%20-%20Serra%2C%20Belo%20Horizonte&t=&z=17&ie=UTF8&iwloc=&output=embed"/></a></section>

  <footer><div className="footer-brand"><img src="/logo-power-shape.png" alt="Power Shape CT"/><h2>Seu próximo treino<br/>começa <i>agora.</i></h2></div><div><p className="eyebrow">ENDEREÇO</p><p>R. do Ouro, 918 — Serra<br/>Belo Horizonte — MG<br/>30220-000</p><a href="https://www.google.com/maps/search/?api=1&query=R.%20do%20Ouro%2C%20918%20Serra%20Belo%20Horizonte" target="_blank" rel="noreferrer">TRAÇAR ROTA ↗</a></div><div><p className="eyebrow">HORÁRIOS</p><p>Seg. a sex. · 05h–22h<br/>Sábado · 08h–15h<br/>Domingo · 09h–12h</p><a href="https://www.instagram.com/powershape_ct" target="_blank" rel="noreferrer">INSTAGRAM ↗</a></div><small>© 2026 POWER SHAPE CT · BELO HORIZONTE</small></footer>
  <a className="whatsapp" href="https://wa.me/553192155412" target="_blank" rel="noreferrer" aria-label="Falar com a Power Shape no WhatsApp">✆<span>Falar no WhatsApp</span></a>

  {modal&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Informações detalhadas" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(null)} aria-label="Fechar">×</button>{modal==='professores'&&<><p className="eyebrow">NOSSA EQUIPE</p><h2>Professores qualificados</h2><p className="prototype-note">Perfis, formações e registros ilustrativos para o protótipo. Substituir pelos dados reais antes da publicação.</p><div className="prof-grid">{professors.map(p=><article key={p.name}><div className={'prof-photo '+p.position}><img src="/professores-grid.png" alt={'Retrato ilustrativo de '+p.name}/></div><div><span>{p.role}</span><h3>{p.name}</h3><b>{p.formation}</b><p>{p.extra}</p><p>{p.bio}</p><small>CREF ilustrativo · confirmar registro real</small></div></article>)}</div></>}{modal==='equipamentos'&&<><p className="eyebrow">ESTRUTURA</p><h2>Equipamentos de ponta</h2><div className="modal-cards visual-cards">{['Musculação|Máquinas guiadas, cabos e estações para treinos precisos.','Cardio|Equipamentos para resistência, aquecimento e condicionamento.','Pesos livres|Halteres, barras e bancos para força e hipertrofia.','Funcional|Acessórios para agilidade, estabilidade e potência.'].map((x,i)=>{const[a,b]=x.split('|');return <article key={a}><div className={'sheet-photo q'+(i+1)}><img src="/equipamentos-grid.png" alt={'Equipamentos ilustrativos para '+a}/></div><h3>{a}</h3><p>{b}</p></article>})}</div></>}{modal==='treinos'&&<><p className="eyebrow">TREINOS PERSONALIZADOS</p><h2>Um caminho para cada objetivo</h2><div className="modal-cards visual-cards">{['Hipertrofia|200–500 kcal/h|Ganho de massa muscular com progressão de cargas.','Emagrecimento|350–650 kcal/h|Combinação de força e condicionamento.','Condicionamento|300–600 kcal/h|Mais fôlego, resistência e disposição.','Intervalado intenso|450–800 kcal/h|Blocos curtos de alta intensidade e recuperação.'].map((x,i)=>{const[a,k,b]=x.split('|');return <article key={a}><div className={'sheet-photo q'+(i+1)}><img src="/treinos-grid.png" alt={'Treino ilustrativo de '+a}/></div><small>ESTIMATIVA MÉDIA</small><h3>{a}</h3><b>{k}</b><p>{b}</p></article>})}</div><p className="prototype-note">Estimativas variam conforme peso, idade, intensidade, condicionamento e duração. Avaliação individual recomendada.</p></>}{modal==='depoimento'&&<><div className={'modal-testimonial-photo '+testimonials[quote].position}><img src="/depoimentos-grid.png" alt={'Retrato ilustrativo de '+testimonials[quote].name}/></div><p className="eyebrow">HISTÓRIA DE ALUNO</p><h2>{testimonials[quote].name}</h2><h3>{testimonials[quote].goal}</h3><blockquote>“{testimonials[quote].text}”</blockquote><p className="prototype-note">Conteúdo ilustrativo para apresentação do protótipo.</p></>}</section></div>}
 </main>
}
